-- Disney catalog seed (utf8mb4). Poster URLs resolved from English Wikipedia pageimages.
SET NAMES utf8mb4;

INSERT INTO studios (id, slug, name) VALUES (1, 'disney', 'Disney');

INSERT INTO sections (id, studio_id, slug, name, period, sort_order) VALUES
(1, 1, 'golden-age', 'Era Dorada', '1937-1942', 1),
(2, 1, 'wartime', 'Era de la Guerra / Películas Paquete', '1942-1949', 2),
(3, 1, 'silver-age', 'Era de Plata', '1950-1967', 3),
(4, 1, 'bronze-age', 'Era de Bronce / Oscura', '1970-1988', 4),
(5, 1, 'renaissance', 'El Renacimiento de Disney', '1989-1999', 5),
(6, 1, 'post-renaissance', 'Post-Renacimiento / Era Post-Clásica', '2000-2008', 6),
(7, 1, 'revival', 'Resurgimiento de Disney / Era 3D', '2009-presente', 7),
(8, 1, 'pixar', 'Pixar', '1995-presente', 8);

INSERT INTO movies (id, section_id, title, original_title, year, wiki_title, poster_url, sort_order) VALUES
(1, 1, 'Blancanieves y los siete enanitos', NULL, 1937, 'Snow White and the Seven Dwarfs (1937 film)', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Snow_White_and_the_Seven_Dwarfs_%28Style_B%29_poster.jpg/500px-Snow_White_and_the_Seven_Dwarfs_%28Style_B%29_poster.jpg', 1),
(2, 1, 'Pinocho', NULL, 1940, 'Pinocchio (1940 film)', 'https://upload.wikimedia.org/wikipedia/en/b/ba/Pinocchio-1940-poster.jpg', 2),
(3, 1, 'Fantasía', NULL, 1940, 'Fantasia (1940 film)', 'https://upload.wikimedia.org/wikipedia/en/6/6b/Fantasia1940.jpg', 3),
(4, 1, 'Dumbo', NULL, 1941, 'Dumbo', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Dumbo-1941-poster.jpg', 4),
(5, 1, 'Bambi', NULL, 1942, 'Bambi', 'https://upload.wikimedia.org/wikipedia/en/8/88/Walt_Disney%27s_Bambi_poster.jpg', 5),
(6, 2, 'Saludos Amigos', NULL, 1942, 'Saludos Amigos', 'https://upload.wikimedia.org/wikipedia/en/a/af/Saludosposter.jpg', 1),
(7, 2, 'Los tres caballeros', NULL, 1944, 'The Three Caballeros', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Three_caballeros_poster.png', 2),
(8, 2, 'Música maestro', NULL, 1946, 'Make Mine Music', 'https://upload.wikimedia.org/wikipedia/en/7/7d/Make_mine_music_poster.png', 3),
(9, 2, 'Las aventuras de Bongo, Mickey y las judías mágicas', 'Fun and Fancy Free', 1947, 'Fun and Fancy Free', 'https://upload.wikimedia.org/wikipedia/en/b/b4/Funfanposter.jpg', 4),
(10, 2, 'Tiempo de melodía', NULL, 1948, 'Melody Time', 'https://upload.wikimedia.org/wikipedia/en/2/26/Melody_Time_poster.jpg', 5),
(11, 2, 'La leyenda de Sleepy Hollow y el Señor Sapo', NULL, 1949, 'The Adventures of Ichabod and Mr. Toad', 'https://upload.wikimedia.org/wikipedia/en/7/77/Ichabodposter.jpg', 6),
(12, 3, 'La Cenicienta', NULL, 1950, 'Cinderella (1950 film)', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1d/1950_is_the_Cinderella_year.jpg/500px-1950_is_the_Cinderella_year.jpg', 1),
(13, 3, 'Alicia en el país de las maravillas', NULL, 1951, 'Alice in Wonderland (1951 film)', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Alice_in_Wonderland_Poster.png/500px-Alice_in_Wonderland_Poster.png', 2),
(14, 3, 'Peter Pan', NULL, 1953, 'Peter Pan (1953 film)', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Peter_Pan_%281953_poster%29.jpg/500px-Peter_Pan_%281953_poster%29.jpg', 3),
(15, 3, 'La dama y el vagabundo', NULL, 1955, 'Lady and the Tramp', 'https://upload.wikimedia.org/wikipedia/en/3/39/Lady-and-tramp-1955-poster.jpg', 4),
(16, 3, 'La bella durmiente', NULL, 1959, 'Sleeping Beauty (1959 film)', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/Sleeping_Beauty_%281959_poster_-_Style_A%29.jpg/500px-Sleeping_Beauty_%281959_poster_-_Style_A%29.jpg', 5),
(17, 3, '101 dálmatas', NULL, 1961, 'One Hundred and One Dalmatians', 'https://upload.wikimedia.org/wikipedia/en/c/cd/One_Hundred_and_One_Dalmatians_movie_poster.jpg', 6),
(18, 3, 'Merlín el encantador', 'The Sword in the Stone', 1963, 'The Sword in the Stone (film)', 'https://upload.wikimedia.org/wikipedia/en/d/d8/SwordintheStonePoster.JPG', 7),
(19, 3, 'El libro de la selva', NULL, 1967, 'The Jungle Book (1967 film)', 'https://upload.wikimedia.org/wikipedia/en/1/1d/Thejunglebook_movieposter.jpg', 8),
(20, 4, 'Los aristogatos', NULL, 1970, 'The Aristocats', 'https://upload.wikimedia.org/wikipedia/en/8/8d/Aristoposter.jpg', 1),
(21, 4, 'Robin Hood', NULL, 1973, 'Robin Hood (1973 film)', 'https://upload.wikimedia.org/wikipedia/en/9/91/Robinhood_1973_poster.png', 2),
(22, 4, 'Lo mejor de Winnie the Pooh', NULL, 1977, 'The Many Adventures of Winnie the Pooh', 'https://upload.wikimedia.org/wikipedia/en/c/c2/The_Many_Adventures_of_Winnie_the_Pooh_poster.jpg', 3),
(23, 4, 'Los rescatadores', NULL, 1977, 'The Rescuers', 'https://upload.wikimedia.org/wikipedia/en/a/ac/Rescuersposter.jpg', 4),
(24, 4, 'Tod y Toby', 'El zorro y el sabueso', 1981, 'The Fox and the Hound', 'https://upload.wikimedia.org/wikipedia/en/7/70/The_Fox_and_the_Hound.jpg', 5),
(25, 4, 'Taron y el caldero mágico', NULL, 1985, 'The Black Cauldron (film)', 'https://upload.wikimedia.org/wikipedia/en/0/0a/The_Black_Cauldron_poster.jpg', 6),
(26, 4, 'Basil, el ratón superdetective', NULL, 1986, 'The Great Mouse Detective', 'https://upload.wikimedia.org/wikipedia/en/a/a4/Mousedetectposter.jpg', 7),
(27, 4, 'Oliver y su pandilla', NULL, 1988, 'Oliver & Company', 'https://upload.wikimedia.org/wikipedia/en/f/fd/Oliver_poster.jpg', 8),
(28, 5, 'La sirenita', NULL, 1989, 'The Little Mermaid (1989 film)', 'https://upload.wikimedia.org/wikipedia/en/c/c0/The_Little_Mermaid_%28Official_1989_Film_Poster%29.png', 1),
(29, 5, 'Los rescatadores en Cangurolandia', NULL, 1990, 'The Rescuers Down Under', 'https://upload.wikimedia.org/wikipedia/en/0/05/Rescuersduposter.jpg', 2),
(30, 5, 'La bella y la bestia', NULL, 1991, 'Beauty and the Beast (1991 film)', 'https://upload.wikimedia.org/wikipedia/en/5/5e/Beauty_and_the_Beast_%281991_film%29_poster.jpg', 3),
(31, 5, 'Aladdín', NULL, 1992, 'Aladdin (1992 Disney film)', 'https://upload.wikimedia.org/wikipedia/en/b/bd/Aladdin_%281992_Disney_film%29_poster.jpg', 4),
(32, 5, 'El rey león', NULL, 1994, 'The Lion King', 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg', 5),
(33, 5, 'Pocahontas', NULL, 1995, 'Pocahontas (1995 film)', 'https://upload.wikimedia.org/wikipedia/en/5/57/Pocahontasposter.jpg', 6),
(34, 5, 'El jorobado de Notre Dame', NULL, 1996, 'The Hunchback of Notre Dame (1996 film)', 'https://upload.wikimedia.org/wikipedia/en/2/26/The_Hunchback_of_Notre_Dame_1996_poster.jpg', 7),
(35, 5, 'Hércules', NULL, 1997, 'Hercules (1997 film)', 'https://upload.wikimedia.org/wikipedia/en/6/65/Hercules_%281997_film%29_poster.jpg', 8),
(36, 5, 'Mulán', NULL, 1998, 'Mulan (1998 film)', 'https://upload.wikimedia.org/wikipedia/en/a/a3/Movie_poster_mulan.JPG', 9),
(37, 5, 'Tarzán', NULL, 1999, 'Tarzan (1999 film)', 'https://upload.wikimedia.org/wikipedia/en/4/4f/Tarzan_%281999_film%29_-_theatrical_poster.jpg', 10),
(38, 6, 'Fantasía 2000', NULL, 1999, 'Fantasia 2000', 'https://upload.wikimedia.org/wikipedia/en/c/c5/Fantasia2000_Poster.jpg', 1),
(39, 6, 'Dinosaurio', NULL, 2000, 'Dinosaur (2000 film)', 'https://upload.wikimedia.org/wikipedia/en/b/bc/Dinosaurmovieposter.jpg', 2),
(40, 6, 'El emperador y sus locuras', 'Las locuras del emperador', 2000, 'The Emperor''s New Groove', 'https://upload.wikimedia.org/wikipedia/en/6/69/Grooveposter.jpg', 3),
(41, 6, 'Atlantis: El imperio perdido', NULL, 2001, 'Atlantis: The Lost Empire', 'https://upload.wikimedia.org/wikipedia/en/d/de/Atlantis_The_Lost_Empire_poster.jpg', 4),
(42, 6, 'Lilo & Stitch', NULL, 2002, 'Lilo & Stitch', 'https://upload.wikimedia.org/wikipedia/en/c/c6/LiloandStitchmovieposter.jpg', 5),
(43, 6, 'El planeta del tesoro', NULL, 2002, 'Treasure Planet', 'https://upload.wikimedia.org/wikipedia/en/7/7e/Treasure_Planet_poster.jpg', 6),
(44, 6, 'Hermano oso', 'Tierra de osos', 2003, 'Brother Bear', 'https://upload.wikimedia.org/wikipedia/en/8/86/Brother_Bear_Poster.png', 7),
(45, 6, 'Zafarrancho en el rancho', 'Vacas vaqueras', 2004, 'Home on the Range (2004 film)', 'https://upload.wikimedia.org/wikipedia/en/b/b9/Homerangeposter.jpg', 8),
(46, 6, 'Chicken Little', NULL, 2005, 'Chicken Little (2005 film)', 'https://upload.wikimedia.org/wikipedia/en/a/a5/Chickenlittlemcgiposter.jpg', 9),
(47, 6, 'Descubriendo a los Robinsons', 'La familia del futuro', 2007, 'Meet the Robinsons', 'https://upload.wikimedia.org/wikipedia/en/d/dc/Meet_the_robinsons.jpg', 10),
(48, 6, 'Bolt', NULL, 2008, 'Bolt (2008 film)', 'https://upload.wikimedia.org/wikipedia/en/4/44/Bolt_ver2.jpg', 11),
(49, 7, 'Tiana y el sapo', 'La princesa y el sapo', 2009, 'The Princess and the Frog', 'https://upload.wikimedia.org/wikipedia/en/8/81/The_Princess_and_the_Frog_poster.jpg', 1),
(50, 7, 'Enredados', NULL, 2010, 'Tangled', 'https://upload.wikimedia.org/wikipedia/en/a/a8/Tangled_poster.jpg', 2),
(51, 7, 'Winnie the Pooh', NULL, 2011, 'Winnie the Pooh (2011 film)', 'https://upload.wikimedia.org/wikipedia/en/e/e2/Winnie_the_Pooh_Poster.jpg', 3),
(52, 7, '¡Rompe Ralph!', 'Ralph el demoledor', 2012, 'Wreck-It Ralph', 'https://upload.wikimedia.org/wikipedia/en/1/15/Wreckitralphposter.jpeg', 4),
(53, 7, 'Frozen: El reino del hielo', NULL, 2013, 'Frozen (2013 film)', 'https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg', 5),
(54, 7, 'Big Hero 6', 'Grandes héroes', 2014, 'Big Hero 6 (film)', 'https://upload.wikimedia.org/wikipedia/en/4/4b/Big_Hero_6_%28film%29_poster.jpg', 6),
(55, 7, 'Zootrópolis', 'Zootopia', 2016, 'Zootopia', 'https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg', 7),
(56, 7, 'Vaiana', 'Moana', 2016, 'Moana (2016 film)', 'https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg', 8),
(57, 7, 'Ralph rompe el internet', 'Ralph el demoledor 2', 2018, 'Ralph Breaks the Internet', 'https://upload.wikimedia.org/wikipedia/en/0/0b/Ralph_Breaks_the_Internet_%282018_film_poster%29.png', 9),
(58, 7, 'Frozen 2', NULL, 2019, 'Frozen II', 'https://upload.wikimedia.org/wikipedia/en/8/89/Frozen_II_%282019_animated_film%29.jpg', 10),
(59, 7, 'Raya y el último dragón', NULL, 2021, 'Raya and the Last Dragon', 'https://upload.wikimedia.org/wikipedia/en/e/ea/Raya_and_the_Last_Dragon.png', 11),
(60, 7, 'Encanto', NULL, 2021, 'Encanto', 'https://upload.wikimedia.org/wikipedia/en/8/83/Encanto_poster.jpg', 12),
(61, 7, 'Mundo Extraño', NULL, 2022, 'Strange World (film)', 'https://upload.wikimedia.org/wikipedia/en/f/fe/Strange_World_poster.jpg', 13),
(62, 7, 'Wish: El poder de los deseos', NULL, 2023, 'Wish (2023 film)', 'https://upload.wikimedia.org/wikipedia/en/d/de/WishMoviePoster.jpg', 14),
(63, 8, 'Toy Story', NULL, 1995, 'Toy Story', 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg', 1),
(64, 8, 'Bichos: Una aventura en miniatura', NULL, 1998, 'A Bug''s Life', 'https://upload.wikimedia.org/wikipedia/en/c/cc/A_Bug%27s_Life.jpg', 2),
(65, 8, 'Toy Story 2', NULL, 1999, 'Toy Story 2', 'https://upload.wikimedia.org/wikipedia/en/c/c0/Toy_Story_2.jpg', 3),
(66, 8, 'Monstruos, S.A.', NULL, 2001, 'Monsters, Inc.', 'https://upload.wikimedia.org/wikipedia/en/6/63/Monsters_Inc.JPG', 4),
(67, 8, 'Buscando a Nemo', NULL, 2003, 'Finding Nemo', 'https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg', 5),
(68, 8, 'Los Increíbles', NULL, 2004, 'The Incredibles', 'https://upload.wikimedia.org/wikipedia/en/2/27/The_Incredibles_%282004_animated_feature_film%29.jpg', 6),
(69, 8, 'Cars', NULL, 2006, 'Cars (film)', 'https://upload.wikimedia.org/wikipedia/en/3/34/Cars_2006.jpg', 7),
(70, 8, 'Ratatouille', NULL, 2007, 'Ratatouille (film)', 'https://upload.wikimedia.org/wikipedia/en/5/50/RatatouillePoster.jpg', 8),
(71, 8, 'WALL·E', NULL, 2008, 'WALL-E', 'https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg', 9),
(72, 8, 'Up', NULL, 2009, 'Up (2009 film)', 'https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg', 10),
(73, 8, 'Toy Story 3', NULL, 2010, 'Toy Story 3', 'https://upload.wikimedia.org/wikipedia/en/6/69/Toy_Story_3_poster.jpg', 11),
(74, 8, 'Cars 2', NULL, 2011, 'Cars 2', 'https://upload.wikimedia.org/wikipedia/en/7/7f/Cars_2_Poster.jpg', 12),
(75, 8, 'Brave', 'Indomable', 2012, 'Brave (2012 film)', 'https://upload.wikimedia.org/wikipedia/en/9/96/Brave_Poster.jpg', 13),
(76, 8, 'Monstruos University', NULL, 2013, 'Monsters University', 'https://upload.wikimedia.org/wikipedia/en/2/2a/Monsters_University_poster_3.jpg', 14),
(77, 8, 'El viaje de Arlo', 'Un gran dinosaurio', 2015, 'The Good Dinosaur', 'https://upload.wikimedia.org/wikipedia/en/8/80/The_Good_Dinosaur_poster.jpg', 15),
(78, 8, 'Del revés', 'Intensamente', 2015, 'Inside Out (2015 film)', 'https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg', 16),
(79, 8, 'Buscando a Dory', NULL, 2016, 'Finding Dory', 'https://upload.wikimedia.org/wikipedia/en/3/3e/Finding_Dory.jpg', 17),
(80, 8, 'Cars 3', NULL, 2017, 'Cars 3', 'https://upload.wikimedia.org/wikipedia/en/9/94/Cars_3_poster.jpg', 18),
(81, 8, 'Coco', NULL, 2017, 'Coco (2017 film)', 'https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg', 19),
(82, 8, 'Los Increíbles 2', NULL, 2018, 'Incredibles 2', 'https://upload.wikimedia.org/wikipedia/en/1/1f/Incredibles_2_%282018_animated_film%29.jpg', 20),
(83, 8, 'Toy Story 4', NULL, 2019, 'Toy Story 4', 'https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg', 21),
(84, 8, 'Onward', 'Unidos', 2020, 'Onward (film)', 'https://upload.wikimedia.org/wikipedia/en/0/03/Onward_poster.jpg', 22),
(85, 8, 'Soul', NULL, 2020, 'Soul (2020 film)', 'https://upload.wikimedia.org/wikipedia/en/3/39/Soul_%282020_film%29_poster.jpg', 23),
(86, 8, 'Luca', NULL, 2021, 'Luca (2021 film)', 'https://upload.wikimedia.org/wikipedia/en/3/33/Luca_%282021_film%29.png', 24),
(87, 8, 'Red', 'Turning Red', 2022, 'Turning Red', 'https://upload.wikimedia.org/wikipedia/en/9/9e/Turning_Red_poster.jpg', 25),
(88, 8, 'Lightyear', NULL, 2022, 'Lightyear (film)', 'https://upload.wikimedia.org/wikipedia/en/f/f9/Lightyear_%28film%29_poster.jpg', 26),
(89, 8, 'Elemental', NULL, 2023, 'Elemental (2023 film)', 'https://upload.wikimedia.org/wikipedia/en/4/4d/Elemental_final_poster.jpg', 27),
(90, 8, 'Del revés 2', 'Intensamente 2', 2024, 'Inside Out 2', 'https://upload.wikimedia.org/wikipedia/en/f/f7/Inside_Out_2_poster.jpg', 28),
(91, 8, 'Elio', NULL, 2025, 'Elio (film)', 'https://upload.wikimedia.org/wikipedia/en/4/4e/Elio_film_poster.jpg', 29);
